name: Run Ayna Fetch Every Hour

on:
  workflow_dispatch:   # ম্যানুয়ালি রান করার জন্য
  schedule:
    - cron: '0 * * * *'  # প্রতি ঘণ্টায় একবার রান করবে

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the script
        run: python ayna.py

      - name: Commit and push updated api.json
        run: |
          git config --local user.email "hasanhabibmottakin@gmail.com"
          git config --local user.name "Hasan Habib Mottakin"
          git add api.json
          git commit -m "Update api.json [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
